from enum import StrEnum


class PyrusResponseErrorCode(StrEnum):
    SERVER_ERROR = 'server_error'
    INVALID_CREDENTIALS = 'invalid_credentials'
    TOKEN_NOT_SPECIFIED = 'token_not_specified'
    REVOKED_TOKEN = 'revoked_token'
    EXPIRED_TOKEN = 'expired_token'
    INVALID_TOKEN = 'invalid_token'
    ACCOUNT_BLOCKED = 'account_blocked'
    AUTHORIZATION_ERROR = 'authorization_error'
    INVALID_FIELD_ID = 'invalid_field_id'
    DELETED_FIELD = 'deleted_field'
    INVALID_FIELD_NAME = 'invalid_field_name'
    INVALID_FIELD_ID_NAME = 'invalid_field_id_name'
    NON_UNIQUE_NAME = 'non_unique_name'
    FIELD_IDENTITY_MISSING = 'field_identity_missing'
    DUPLICATE_FIELD = 'duplicate_field'
    INVALID_CATALOG_ID = 'invalid_catalog_id'
    INVALID_CATALOG_ITEM_NAME = 'invalid_catalog_item_name'
    NON_UNIQUE_CATALOG_ITEM_NAME = 'non_unique_catalog_item_name'
    INVALID_CATALOG_ITEM_ID = 'invalid_catalog_item_id'
    CATALOG_ITEM_ID_NAME_MISMATCH = 'catalog_item_id_name_mismatch'
    INVALID_EMAIL = 'invalid_email'
    NON_UNIQUE_EMAIL = 'non_unique_email'
    INVALID_PERSON_ID = 'invalid_person_id'
    INVALID_PERSON_ID_EMAIL = 'invalid_person_id_email'
    FORM_HAS_NO_TASK = 'form_has_no_task'
    UNRECOGNIZED_ATTACHMENT_ID = 'unrecognized_attachment_id'
    REQUIRED_FIELD_MISSING = 'required_field_missing'
    TYPE_IS_NOT_SUPPORTED = 'type_is_not_supported'
    CATALOG_IDENTITY_MISSING = 'catalog_identity_missing'
    INCORRECT_PARAMETERS_COUNT = 'incorrect_parameters_count'
    FILTER_TYPE_IS_NOT_SUPPORTED = 'filter_type_is_not_supported'
    STEP_FIELD_DOES_NOT_EXISTS = 'step_field_does_not_exists'
    CATALOG_ITEM_ID_MISSING = 'catalog_item_id_missing'
    PERSON_IDENTITY_MISSING = 'person_identity_missing'
    EITHER_DUE_DATE_OR_DUE_CAN_BE_SET = 'either_due_date_or_due_can_be_set'
    NEGATIVE_DURATION = 'negative_duration'
    DURATION_IS_TOO_LONG = 'duration_is_too_long'
    DUE_MISSING = 'due_missing'
    SCHEDULED_DATE_IN_PAST = 'scheduled_date_in_past'
    CANNOT_ADD_FORM_PROJECT = 'cannot_add_form_project'
    FORM_TEMPLATE_CANT_BE_REMOVED_FROM_TASK = 'form_template_cant_be_removed_from_task'
    NO_FILE_IN_REQUEST = 'no_file_in_request'
    TOO_LARGE_REQUEST_LENGTH = 'too_large_request_length'
    REQUIRED_PARAMETER_MISSING = 'required_parameter_missing'
    INVALID_VALUE_FORMAT = 'invalid_value_format'
    TOO_MANY_TASK_STEPS = 'too_many_task_steps'
    TOO_MANY_COMMENTS = 'too_many_comments'
    INVALID_STEP_NUMBER = 'invalid_step_number'
    TASK_LIMIT_EXCEEDED = 'task_limit_exceeded'
    FIELD_IS_IN_TABLE = 'field_is_in_table'
    REQUIRED_TABLE_FIELD_MISSING = 'required_table_field_missing'
    DEPARTMENT_CATALOG_CAN_NOT_BE_MODIFIED = 'department_catalog_can_not_be_modified'
    CATALOG_DUPLICATE_ROWS = 'catalog_duplicate_rows'
    EMPTY_CATALOG_HEADERS = 'empty_catalog_headers'
    CAN_NOT_MODIFY_DELETED_CATALOG = 'can_not_modify_deleted_catalog'
    CAN_NOT_MODIFY_FIRST_COLUMN = 'can_not_modify_first_column'
    CATALOG_HEADERS_ITEMS_MISMATCH = 'catalog_headers_items_mismatch'
    TOO_MANY_CATALOG_ITEMS = 'too_many_catalog_items'
    CATALOG_ITEM_MAX_LENGTH_EXCEEDED = 'catalog_item_max_length_exceeded'
    CATALOG_DUPLICATE_HEADERS = 'catalog_duplicate_headers'
    INVALID_JSON = 'invalid_json'
    EMPTY_BODY = 'empty_body'
    ACCESS_DENIED_PROJECT = 'access_denied_project'
    ACCESS_DENIED_TASK = 'access_denied_task'
    ACCESS_DENIED_CLOSE_TASK = 'access_denied_close_task'
    ACCESS_DENIED_REOPEN_TASK = 'access_denied_reopen_task'
    ACCESS_DENIED_CATALOG = 'access_denied_catalog'
    ACCESS_DENIED_FORM = 'access_denied_form'
    ACCESS_DENIED_PERSON = 'access_denied_person'
    TOO_MANY_REQUESTS = 'too_many_requests'
    EMPTY_FILE = 'empty_file'
    BAD_MULTIPART_CONTENT = 'bad_multipart_content'
    INVALID_TABLE_ROW = 'invalid_table_row'
    CANNOT_ADD_EXTERNAL_USER = 'cannot_add_external_user'
    OPTION_IS_NOT_SUPPORTED = 'option_is_not_supported'
    NO_RIGHTS_TO_SEND_SMS = 'no_rights_to_send_sms'
    SMS_INTEGRATION_NOT_CONFIGURED = 'sms_integration_not_configured'
    INVALID_APPLICATION_ID = 'invalid_application_id'
    TEXT_MISSING = 'text_missing'
    FORM_ID_MISSING = 'form_id_missing'
    SINGLE_VALUE_IS_NOT_SUPPORTED = 'single_value_is_not_supported'
    PARTICIPANT_LIMIT_EXCEEDED = 'participant_limit_exceeded'
    TABLE_ROWS_LIMIT_EXCEEDED = 'table_rows_limit_exceeded'
    TEXT_FIELD_VALUE_LIMIT_EXCEEDED = 'text_field_value_limit_exceeded'
    UNABLE_TO_EDIT_FIELD = 'unable_to_edit_field'
    TOO_MANY_DECIMAL_PLACES = 'too_many_decimal_places'
    EXTERNAL_COMMENT_EMPTY_TEXT = 'external_comment_empty_text'
    SENDER_ADDRESS_FIELD_MISSING = 'sender_address_field_missing'
    EXTERNAL_COMMENT_RECIPIENT_NOT_FOUND = 'external_comment_recipient_not_found'
    DEFAULT_MAILBOX_NOT_FOUND = 'default_mailbox_not_found'
    CATALOG_NULL_VALUE = 'catalog_null_value'
    MAX_TEXT_LENGTH_EXCEEDED = 'max_text_length_exceeded'
    DUE_OUTSIDE_OF_BOUNDS = 'due_outside_of_bounds'
    ATTACHMENTS_FORBIDDEN = 'attachments_forbidden'
    UNRECOGNIZED_CALL_GUID = 'unrecognized_call_guid'
    UNSUPPORTED_ATTACHMENT_FORMAT = 'unsupported_attachment_format'
    VALIDATION_ERROR = 'validation_error'
    ACCESS_DENIED_FILE_ACCESS_HISTORY = 'access_denied_file_access_history'
    ACCESS_DENIED_FILE = 'access_denied_file'
    ACCESS_DENIED_REPORT = 'access_denied_report'
    ACCESS_DENIED = 'access_denied'
    FILE_LIMIT_EXCEEDED = 'file_limit_exceeded'
    LIMIT_EXCEEDED = 'limit_exceeded'
    ITEMS_COUNT_OUT_OF_RANGE = 'items_count_out_of_range'
    PRIVATE_COMMENT_HAS_FORBIDDEN_CHANGES = 'private_comment_has_forbidden_changes'
    PRIVATE_CHANNEL_ACCESS_DENIED = 'private_channel_access_denied'


class PyrusPersonType(StrEnum):
    USER = 'user'
    ROLE = 'role'
    BOT = 'bot'


class PyrusApprovalChoice(StrEnum):
    APPROVED = 'approved'
    REJECTED = 'rejected'
    ACKNOWLEDGED = 'acknowledged'
    REVOKED = 'revoked'
    WAITING = 'waiting'


class PyrusTaskAction(StrEnum):
    FINISHED = 'finished'
    REOPENED = 'reopened'


class PyrusChannelType(StrEnum):
    EMAIL = 'email'
    TELEGRAM = 'telegram'
    FACEBOOK = 'facebook'
    VK = 'vk'
    VIBER = 'viber'
    MOBILE_APP = 'mobile_app'
    WEB_WIDGET = 'web_widget'
    AVITO_JOB = 'avito_job'
    AVITO_MESSENGER = 'avito_messenger'
    ZADARMA = 'zadarma'
    AMO_CRM = 'amo_crm'


class PyrusFormFieldType(StrEnum):
    TEXT = 'text'
    MONEY = 'money'
    NUMBER = 'number'
    DATE = 'date'
    TIME = 'time'
    CHECKMARK = 'checkmark'
    DUE_DATE = 'due_date'
    DUE_DATE_TIME = 'due_date_time'
    EMAIL = 'email'
    PHONE = 'phone'
    FLAG = 'flag'
    STEP = 'step'
    STATUS = 'status'
    CREATION_DATE = 'creation_date'
    NOTE = 'note'
    PERSON = 'person'
    AUTHOR = 'author'
    FORM_LINK = 'form_link'
    FILE = 'file'
    CATALOG = 'catalog'
    MULTIPLE_CHOICE = 'multiple_choice'
    TABLE = 'table'
    TITLE = 'title'
